name: CI/CD Pipeline for voting application

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name containeregistryy

      - name: Build vote image
        run: docker build ./vote -t containeregistryy.azurecr.io/vote:${{ github.sha }}

      - name: Push vote image
        run: docker push containeregistryy.azurecr.io/vote:${{ github.sha }}

      - name: Build worker image
        run: docker build ./worker -t containeregistryy.azurecr.io/worker:${{ github.sha }}

      - name: Push worker image
        run: docker push containeregistryy.azurecr.io/worker:${{ github.sha }}

      - name: Build result image
        run: docker build ./result -t containeregistryy.azurecr.io/result:${{ github.sha }}

      - name: Push result image
        run: docker push containeregistryy.azurecr.io/result:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: Multi-node-Cluster 
          resource-group: CICDpipelineWithAzureDevops


      - name: Deploy to AKS
        run: kubectl apply -f k8s-specifications/
